run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable-all: true
    
  depguard:
    rules:
      main:
        files:
          - "**/*.go"
        allow:
          - $gostd
          - github.com/tonimelisma/onedrive-client
          - github.com/gofrs/flock
          - golang.org/x/oauth2
          - github.com/stretchr/testify

  gocyclo:
    min-complexity: 15
    
  goimports:
    local-prefixes: github.com/tonimelisma/onedrive-client
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - paramTypeCombine
      - unnamedResult
      - whyNoLint
      - wrapperFunc

  dupl:
    threshold: 100

  funlen:
    lines: 100
    statements: 50

  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers: 
      - '0'
      - '1'
      - '2'
      - '3'
      - '200'
      - '201'
      - '400'
      - '401'
      - '403'
      - '404'
      - '429'
      - '500'

  goconst:
    min-len: 2
    min-occurrences: 2

  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G204 # Audit use of command execution
      - G304 # Audit file path provided as taint input
      - G307 # Audit deferred close

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

  stylecheck:
    checks: ["all", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

  unparam:
    check-exported: false

  unused:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false

  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  enable:
    - bodyclose
    - unused         # replaces: deadcode, structcheck, varcheck
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - copyloopvar    # replaces: exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - mnd            # replaces: gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - unused
      text: "var .* is unused"
    - path: _test\.go
      linters:
        - mnd
        - gocritic
        - funlen
        - dupl
        - gosec
    - path: main\.go
      linters:
        - gocritic
    - path: cmd/
      linters:
        - gocritic
    - path: examples/
      linters:
        - gocritic
        - mnd
        - unused
    - path: e2e/
      linters:
        - gocritic
        - mnd
        - funlen
        - dupl
        - gosec
    - text: "G104:"
      linters:
        - gosec
    - text: "G204:"
      linters:
        - gosec
    - text: "G304:"
      linters:
        - gosec
    - text: "G307:"
      linters:
        - gosec

  fix: false
  max-issues-per-linter: 0
  max-same-issues: 0 