run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
    
  golint:
    min-confidence: 0.8
    
  gocyclo:
    min-complexity: 15
    
  goimports:
    local-prefixes: github.com/tonimelisma/onedrive-client
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - wrapperFunc

  dupl:
    threshold: 100

  exhaustive:
    default-signifies-exhaustive: false

  funlen:
    lines: 100
    statements: 50

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/tonimelisma/onedrive-client)

  godot:
    scope: declarations
    exclude:
      - "^fixme:"
      - "^todo:"
    period: true
    capital: false

  gofmt:
    simplify: true

  gofumpt:
    extra-rules: true

  goheader:
    values:
      const:
        COMPANY: tonimelisma
    template: |-
      Copyright (c) {{ YEAR }} {{ COMPANY }}
      SPDX-License-Identifier: MIT

  gomnd:
    ignored-numbers:
      - '0666'
      - '0755'
      - '42'

  gomodguard:
    allowed:
      modules:
        - github.com/golang/oauth2
        - github.com/spf13/cobra
        - github.com/schollz/progressbar

  goprintffuncname:
    funcs:
      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  gosec:
    severity: "low"
    confidence: "low"
    excludes:
      - G304 # file path provided as taint input
      - G404 # insecure random number source (rand)

  gosimple:
    checks: [ "all" ]

  gostaticcheck:
    checks: [ "all" ]

  lll:
    line-length: 140

  maligned:
    suggest-new: true

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  staticcheck:
    checks: [ "all" ]

  stylecheck:
    checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]

  testpackage:
    skip-regexp: (export|internal)_test\.go

  unparam:
    check-exported: false

  unused:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - gostaticcheck
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo

    - path: cmd/
      linters:
        - gochecknoinits

    - path: pkg/onedrive/models\.go
      linters:
        - lll
        - maligned

  exclude:
    # for "public interface + private struct implementation" cases only!
    - '`.*` is unused'

  max-issues-per-linter: 0
  max-same-issues: 0 